# Generated by Django 5.2.8 on 2026-03-07 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_name', models.CharField(help_text='e.g. video_to_audio:index', max_length=100, unique=True, verbose_name='Tool ID (URL name)')),
                ('name', models.CharField(max_length=100, verbose_name='Tool Name')),
                ('desc', models.CharField(max_length=255, verbose_name='Description')),
                ('icon', models.CharField(help_text='e.g. bi-scissors', max_length=50, verbose_name='Bootstrap Icon Class')),
                ('category', models.CharField(choices=[('pdf', 'PDF'), ('image', 'Image'), ('text', 'Text'), ('other', 'Other')], max_length=20, verbose_name='Category')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active (Visible)')),
                ('order', models.IntegerField(default=0, verbose_name='Display Order')),
            ],
            options={
                'verbose_name': 'Tool',
                'verbose_name_plural': 'Tools',
                'ordering': ['order', 'name'],
            },
        ),
    ]
