# Generated by Django 5.2.8 on 2026-03-07 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ad Name')),
                ('position', models.CharField(choices=[('sidebar_left', 'Sidebar Left'), ('sidebar_right', 'Sidebar Right'), ('header_banner', 'Header Banner'), ('footer_banner', 'Footer Banner'), ('in_content', 'In Content')], max_length=20, verbose_name='Position')),
                ('page', models.CharField(choices=[('all', 'All Pages'), ('home', 'Home Page Only'), ('tools', 'Tool Pages Only')], default='all', max_length=20, verbose_name='Show On')),
                ('ad_code', models.TextField(help_text='Paste your Google AdSense or ad network HTML code here.', verbose_name='Ad Code (HTML)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
            ],
            options={
                'verbose_name': 'Ad Placement',
                'verbose_name_plural': 'Ad Placements',
                'ordering': ['position', 'order'],
            },
        ),
    ]
