# Generated by Django 5.2.8 on 2026-03-08 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text="Internal key, e.g. 'about', 'contact', 'privacy', 'terms', 'faq'.", max_length=50, unique=True)),
                ('slug', models.SlugField(help_text="URL slug, e.g. 'about', 'contact'.", max_length=100, unique=True)),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('content', models.TextField(blank=True, verbose_name='Content')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active (visible)')),
                ('show_in_nav', models.BooleanField(default=True, verbose_name='Show in main menu')),
                ('show_in_footer', models.BooleanField(default=False, verbose_name='Show in footer')),
                ('nav_order', models.IntegerField(default=100, verbose_name='Menu order')),
                ('footer_order', models.IntegerField(default=100, verbose_name='Footer order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Static Page',
                'verbose_name_plural': 'Static Pages',
                'ordering': ['nav_order', 'title'],
            },
        ),
    ]
