# Generated by Django 5.2.8 on 2026-03-08 06:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VisitStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('path', models.CharField(max_length=512)),
                ('country_code', models.CharField(blank=True, max_length=2)),
                ('device_type', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet'), ('bot', 'Bot'), ('other', 'Other')], default='other', max_length=10)),
                ('visits', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Visit Stat',
                'verbose_name_plural': 'Visit Stats',
                'ordering': ('-date', '-visits'),
                'unique_together': {('date', 'path', 'country_code', 'device_type')},
            },
        ),
    ]
