# Generated by Django 5.2.8 on 2026-03-07 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeployLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('running', 'Running')], default='running', max_length=10, verbose_name='Status')),
                ('branch', models.CharField(default='main', max_length=100, verbose_name='Branch')),
                ('commit_before', models.CharField(blank=True, max_length=40, verbose_name='Commit Before')),
                ('commit_after', models.CharField(blank=True, max_length=40, verbose_name='Commit After')),
                ('output', models.TextField(blank=True, verbose_name='Output')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Triggered At')),
                ('triggered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Triggered By')),
            ],
            options={
                'verbose_name': 'Deploy Log',
                'verbose_name_plural': 'Deploy Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
